FROM node:14.16.1 as front-builder

WORKDIR /usr/src/app

COPY front/ ./front/
RUN cd front && rm -rf node_modules/
RUN cd front && npm i && npm run build

FROM nginx:alpine

RUN rm /etc/nginx/nginx.conf /etc/nginx/mime.types
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./.nginx/mime.types /etc/nginx/mime.types

RUN rm -rf /usr/share/nginx/html/*

COPY --from=front-builder /usr/src/app/front/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# docker build -t vader/vue-app .
# docker run -it -p 8081:8081 --rm --name vue-docker-app vader/vue-app
# az acr update -n vueApp --admin-enabled true
# az acr build --image vue-docker-azure_vue-ui:v4 --registry vueApp --file Dockerfile-front .
